spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true

# ex)
# http://api.currencylayer.com/live
#
#    ? access_key = YOUR_ACCESS_KEY
#    & source = GBP
#    & currencies = USD,AUD,CAD,PLN,MXN
#    & format = 1
currency:
  url: http://api.currencylayer.com/live
  accessKey: 59c49f2635b3e2a05fa1d2b4de9f582a

